import io
import json
import os
import re
import traceback

from difflib import SequenceMatcher
from enum import Enum
from typing import List, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, Query, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from google import genai
from google.genai import types
import pdfplumber
from pydantic import BaseModel, Field


# ============================================================================
# ENVIRONMENT
# ============================================================================

load_dotenv()


# ============================================================================
# GEMINI CONFIGURATION
# ============================================================================

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

GEMINI_MODEL = os.getenv(
    "GEMINI_MODEL",
    "gemini-3.6-flash",
)


# ============================================================================
# FASTAPI APP
# ============================================================================

app = FastAPI(
    title="Vistara Contract Analysis API",
    description="AI-powered contract risk analysis using Google Gemini",
    version="1.0.0",
)


# ============================================================================
# CORS
# ============================================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================================
# DATA MODELS
# ============================================================================

class SeverityLevel(str, Enum):
    high = "High"
    medium = "Medium"
    low = "Low"


class ClauseRisk(BaseModel):
    clause_text: str
    severity: SeverityLevel
    category: str
    plain_explanation: str
    worst_case_scenario: str

    # ------------------------------------------------------------------------
    # Evidence verification fields.
    #
    # These are NOT generated by Gemini.
    # They are calculated by Vistara after Gemini responds.
    # ------------------------------------------------------------------------

    evidence_verified: bool = False

    match_confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    matched_page: Optional[int] = None


class ContractReport(BaseModel):
    filename: str
    overall_score: int = Field(..., ge=0, le=100)
    risk_level: str
    high_risk_count: int
    medium_risk_count: int
    low_risk_count: int
    flagged_clauses: List[ClauseRisk]


# ============================================================================
# INTERNAL PAGE MODEL
# ============================================================================

class ExtractedPage(BaseModel):
    page_number: int
    text: str


# ============================================================================
# MOCK REPORT
#
# This remains ONLY for /analyze?mock=true.
# It is not used by the real dynamic analysis path.
# ============================================================================

MOCK_REPORT = ContractReport(
    filename="apartment_lease_mock.pdf",
    overall_score=28,
    risk_level="High",
    high_risk_count=2,
    medium_risk_count=1,
    low_risk_count=1,
    flagged_clauses=[
        ClauseRisk(
            clause_text=(
                "This lease shall automatically renew for successive one-year terms "
                "unless Tenant provides written notice of non-renewal at least 90 days "
                "prior to the end of the then-current term."
            ),
            severity=SeverityLevel.high,
            category="Automatic Renewal",
            plain_explanation=(
                "Your lease renews itself for another full year unless you send a "
                "formal written notice 90 days before it ends. Missing that window "
                "locks you in."
            ),
            worst_case_scenario=(
                "You forget to send notice in time, get automatically locked into "
                "another 12-month lease, and owe a full year's rent even if you "
                "need to move out."
            ),
            evidence_verified=cd.,
            match_confidence=1.0,
            matched_page=1,
        ),
        ClauseRisk(
            clause_text=(
                "Tenant shall be solely responsible for any and all damages to the "
                "premises, including structural repairs, plumbing, electrical systems, "
                "and appliances, regardless of cause."
            ),
            severity=SeverityLevel.high,
            category="Liability",
            plain_explanation=(
                "You are on the hook for all repairs — even things that break through "
                "normal wear, pre-existing issues, or causes outside your control."
            ),
            worst_case_scenario=(
                "A pipe bursts due to building age, and you are billed thousands of "
                "dollars for structural repairs that are legally the landlord's "
                "responsibility."
            ),
            evidence_verified=True,
            match_confidence=1.0,
            matched_page=1,
        ),
        ClauseRisk(
            clause_text=(
                "Landlord may enter the premises at any time with or without notice "
                "for inspection, maintenance, or any other purpose deemed necessary."
            ),
            severity=SeverityLevel.medium,
            category="Privacy / Entry Rights",
            plain_explanation=(
                "The landlord can walk in whenever they want without telling you "
                "first, which violates standard tenant privacy rights in many "
                "jurisdictions."
            ),
            worst_case_scenario=(
                "Your landlord enters repeatedly without warning, disrupting your "
                "life and potentially violating local tenant protection laws."
            ),
            evidence_verified=True,
            match_confidence=1.0,
            matched_page=1,
        ),
        ClauseRisk(
            clause_text=(
                "Tenant agrees to keep noise levels to a minimum after 9:00 PM "
                "on weekdays."
            ),
            severity=SeverityLevel.low,
            category="Noise / Conduct",
            plain_explanation=(
                "Standard quiet-hours clause, earlier than typical but not unusual."
            ),
            worst_case_scenario=(
                "Landlord uses a minor noise complaint as grounds to initiate "
                "eviction proceedings."
            ),
            evidence_verified=True,
            match_confidence=1.0,
            matched_page=1,
        ),
    ],
)


# ============================================================================
# TEXT NORMALIZATION
# ============================================================================

def normalize_text(text: str) -> str:
    """
    Normalize text for evidence comparison.

    This intentionally preserves words and numbers.

    It only normalizes formatting differences such as:
    - casing
    - whitespace
    - common quote variations
    - dash variations
    - soft hyphens
    """

    if not text:
        return ""

    text = text.replace("\u00ad", "")

    # Normalize common quote characters.
    text = (
        text.replace("“", '"')
        .replace("”", '"')
        .replace("‘", "'")
        .replace("’", "'")
    )

    # Normalize different dash characters.
    text = (
        text.replace("–", "-")
        .replace("—", "-")
        .replace("−", "-")
    )

    # Lowercase.
    text = text.lower()

    # Collapse all whitespace.
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def normalize_for_matching(text: str) -> str:
    """
    More tolerant normalization used only for fuzzy evidence matching.

    It keeps letters and numbers, but removes punctuation that can differ
    between PDF extraction and Gemini's copied evidence.
    """

    text = normalize_text(text)

    # Keep unicode letters/numbers and spaces.
    text = re.sub(
        r"[^\w\s₹]",
        " ",
        text,
        flags=re.UNICODE,
    )

    text = re.sub(r"\s+", " ", text)

    return text.strip()


# ============================================================================
# PDF TEXT EXTRACTION
# ============================================================================

def extract_pdf_pages(
    file_bytes: bytes,
) -> List[ExtractedPage]:
    """
    Extract text page-by-page.

    Keeping page boundaries is important because later we need to know
    where Gemini's evidence actually occurs.
    """

    pages: List[ExtractedPage] = []

    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        for page_number, page in enumerate(
            pdf.pages,
            start=1,
        ):
            try:
                page_text = page.extract_text() or ""
            except Exception as e:
                print(
                    f"⚠️ PDF page {page_number} extraction failed: {e}"
                )
                page_text = ""

            page_text = page_text.strip()

            pages.append(
                ExtractedPage(
                    page_number=page_number,
                    text=page_text,
                )
            )

    return pages


def combine_pages(
    pages: List[ExtractedPage],
) -> str:
    """
    Combine page text for Gemini while preserving page boundaries.
    """

    parts: List[str] = []

    for page in pages:
        if not page.text.strip():
            continue

        parts.append(
            f"\n--- PAGE {page.page_number} ---\n"
            f"{page.text}"
        )

    return "\n".join(parts).strip()


# ============================================================================
# RAW TEXT EXTRACTION
# ============================================================================

def extract_text_input(
    text: str,
) -> List[ExtractedPage]:
    """
    Convert raw text input into the same internal page representation.

    Raw text has no real PDF page information, so it is treated as one
    logical page.
    """

    return [
        ExtractedPage(
            page_number=1,
            text=text.strip(),
        )
    ]


# ============================================================================
# EVIDENCE VERIFICATION
# ============================================================================

def exact_normalized_match(
    clause_text: str,
    document_text: str,
) -> bool:
    """
    Check whether the Gemini clause exists in the document after
    formatting normalization.
    """

    clause = normalize_text(clause_text)
    document = normalize_text(document_text)

    if not clause or not document:
        return False

    return clause in document


def tolerant_exact_match(
    clause_text: str,
    document_text: str,
) -> bool:
    """
    More tolerant exact comparison.

    Useful when punctuation or line formatting differs.
    """

    clause = normalize_for_matching(clause_text)
    document = normalize_for_matching(document_text)

    if not clause or not document:
        return False

    return clause in document


# ============================================================================
# FUZZY MATCHING HELPERS
# ============================================================================

def tokenize_matching_text(
    text: str,
) -> List[str]:
    normalized = normalize_for_matching(text)

    if not normalized:
        return []

    return normalized.split()


def similarity(
    a: str,
    b: str,
) -> float:
    if not a or not b:
        return 0.0

    return SequenceMatcher(
        None,
        a,
        b,
    ).ratio()


def fuzzy_clause_match(
    clause_text: str,
    document_text: str,
) -> float:
    """
    Find a likely location of the Gemini clause in document text.

    Returns a confidence score from 0.0 to 1.0.

    This is deliberately conservative:
    it does not treat a tiny 2-3 word phrase as a valid clause.
    """

    clause_tokens = tokenize_matching_text(
        clause_text
    )

    document_tokens = tokenize_matching_text(
        document_text
    )

    if not clause_tokens or not document_tokens:
        return 0.0

    # Extremely short Gemini evidence is unsafe to locate.
    if len(clause_tokens) < 8:
        return 0.0

    clause_joined = " ".join(
        clause_tokens
    )

    target_length = len(clause_tokens)

    # We search around the expected clause length.
    min_window = max(
        8,
        int(target_length * 0.80),
    )

    max_window = min(
        len(document_tokens),
        max(
            min_window,
            int(target_length * 1.20),
        ),
    )

    best_score = 0.0

    # ------------------------------------------------------------------------
    # Use the first and last words as anchors.
    #
    # This prevents generic phrases such as:
    #
    #   "before the expiration"
    #
    # from becoming the basis of a match.
    # ------------------------------------------------------------------------

    anchor_size = min(
        6,
        max(
            3,
            len(clause_tokens) // 4,
        ),
    )

    start_anchor = " ".join(
        clause_tokens[:anchor_size]
    )

    end_anchor = " ".join(
        clause_tokens[-anchor_size:]
    )

    # ------------------------------------------------------------------------
    # Find candidate locations using the beginning anchor.
    # ------------------------------------------------------------------------

    candidate_starts: List[int] = []

    for index in range(
        0,
        len(document_tokens) - anchor_size + 1,
    ):
        candidate = " ".join(
            document_tokens[
                index:index + anchor_size
            ]
        )

        anchor_score = similarity(
            start_anchor,
            candidate,
        )

        if anchor_score >= 0.72:
            candidate_starts.append(index)

    # ------------------------------------------------------------------------
    # If no strong beginning anchor exists, don't blindly scan every phrase.
    # ------------------------------------------------------------------------

    if not candidate_starts:
        return 0.0

    for start_index in candidate_starts:
        for window_size in range(
            min_window,
            max_window + 1,
        ):
            end_index = (
                start_index + window_size
            )

            if end_index > len(document_tokens):
                break

            candidate_tokens = document_tokens[
                start_index:end_index
            ]

            candidate_text = " ".join(
                candidate_tokens
            )

            full_score = similarity(
                clause_joined,
                candidate_text,
            )

            if full_score < best_score:
                continue

            # --------------------------------------------------------------
            # End-anchor verification.
            # --------------------------------------------------------------

            if len(candidate_tokens) >= anchor_size:
                candidate_end_anchor = " ".join(
                    candidate_tokens[
                        -anchor_size:
                    ]
                )

                end_score = similarity(
                    end_anchor,
                    candidate_end_anchor,
                )
            else:
                end_score = 0.0

            # --------------------------------------------------------------
            # Combined confidence.
            # --------------------------------------------------------------

            combined_score = (
                (full_score * 0.70)
                + (end_score * 0.30)
            )

            if combined_score > best_score:
                best_score = combined_score

    return best_score


# ============================================================================
# VERIFY CLAUSE AGAINST DOCUMENT
# ============================================================================

def verify_clause_evidence(
    clause_text: str,
    pages: List[ExtractedPage],
) -> tuple[bool, float, Optional[int]]:
    """
    Verify Gemini's clause against the actual supplied document.

    Returns:

        evidence_verified
        confidence
        matched_page
    """

    if not clause_text.strip():
        return False, 0.0, None

    # ------------------------------------------------------------------------
    # 1. Strong exact match.
    # ------------------------------------------------------------------------

    for page in pages:
        if not page.text.strip():
            continue

        if exact_normalized_match(
            clause_text,
            page.text,
        ):
            return True, 1.0, page.page_number

    # ------------------------------------------------------------------------
    # 2. Tolerant exact match.
    # ------------------------------------------------------------------------

    for page in pages:
        if not page.text.strip():
            continue

        if tolerant_exact_match(
            clause_text,
            page.text,
        ):
            return True, 0.98, page.page_number

    # ------------------------------------------------------------------------
    # 3. Controlled fuzzy matching.
    #
    # We do NOT accept weak fuzzy matches.
    # ------------------------------------------------------------------------

    best_confidence = 0.0
    best_page: Optional[int] = None

    for page in pages:
        if not page.text.strip():
            continue

        score = fuzzy_clause_match(
            clause_text,
            page.text,
        )

        if score > best_confidence:
            best_confidence = score
            best_page = page.page_number

    # ------------------------------------------------------------------------
    # Conservative verification threshold.
    #
    # This is intentionally not based on any specific document.
    # ------------------------------------------------------------------------

    if best_confidence >= 0.88:
        return (
            True,
            round(best_confidence, 4),
            best_page,
        )

    return (
        False,
        round(best_confidence, 4),
        best_page,
    )


# ============================================================================
# VERIFY COMPLETE REPORT
# ============================================================================

def verify_report_evidence(
    report: ContractReport,
    pages: List[ExtractedPage],
) -> ContractReport:
    """
    Verify every Gemini-generated risk finding.

    Gemini determines the risk.

    This function only verifies whether the evidence exists in the
    actual supplied document.
    """

    verified_clauses: List[ClauseRisk] = []

    print(
        "========================================"
    )
    print(
        "VISTARA EVIDENCE VERIFICATION STARTED"
    )
    print(
        f"Clauses to verify: "
        f"{len(report.flagged_clauses)}"
    )
    print(
        "========================================"
    )

    for index, clause in enumerate(
        report.flagged_clauses,
        start=1,
    ):
        verified, confidence, page_number = (
            verify_clause_evidence(
                clause_text=clause.clause_text,
                pages=pages,
            )
        )

        updated_clause = clause.model_copy(
            update={
                "evidence_verified": verified,
                "match_confidence": confidence,
                "matched_page": page_number,
            }
        )

        verified_clauses.append(
            updated_clause
        )

        print(
            f"Clause {index}: "
            f"[{clause.severity.value}] "
            f"verified={verified} "
            f"confidence={confidence:.3f} "
            f"page={page_number}"
        )

    print(
        "========================================"
    )
    print(
        "VISTARA EVIDENCE VERIFICATION FINISHED"
    )
    print(
        "========================================"
    )

    return report.model_copy(
        update={
            "flagged_clauses": verified_clauses
        }
    )


# ============================================================================
# GEMINI SYSTEM PROMPT
# ============================================================================

SYSTEM_PROMPT = """
You are Vistara, an expert contract risk analysis AI.

Your task is to analyze ONLY the contract provided in the user input.

Your primary goal is to identify materially relevant clauses that may create risk
for the party reviewing the contract.

Potential risk areas include:

- financial risks
- liabilities
- unfair obligations
- termination penalties
- automatic renewals
- privacy concerns
- unusual restrictions
- excessive responsibilities
- indemnification obligations
- one-sided rights
- payment obligations
- penalties or fees
- restrictive conditions
- potentially unfavorable conditions

EVIDENCE AND CLAUSE EXTRACTION:

For every materially relevant risky clause:

1. Return the EXACT wording of the relevant clause as it appears in the supplied
   contract.

2. Do NOT paraphrase, rewrite, summarize, reconstruct, or invent the clause_text.

3. Preserve important details exactly, including:
   - numbers
   - dates
   - monetary amounts
   - percentages
   - time periods
   - conditions
   - defined terms
   - punctuation where possible

4. Do not combine multiple unrelated clauses into one clause_text.

5. Do not create clause_text from your understanding of the contract.

6. If the contract contains a long risky provision, return the complete relevant
   provision rather than an isolated sentence whenever possible.

7. The clause_text must be directly supported by the supplied contract text.

8. If you cannot identify the exact wording of a risky clause from the supplied
   contract, do NOT invent or reconstruct it.

RISK CLASSIFICATION:

For every flagged clause:

- Assign exactly one severity:
  High, Medium, or Low.

- Give exactly one clear risk category.

- Explain the clause in simple plain English.

- Explain a realistic worst-case scenario based on the actual clause.

Do not claim that something is legally invalid or illegal unless that conclusion
is explicitly supported by the supplied contract context.

Do not assume laws, regulations, jurisdictions, or facts that are not provided
in the contract.

SCORING:

- overall_score must be an integer from 0 to 100.
- 0 = extremely hazardous.
- 100 = very safe.

The score should reflect the overall level and number of materially relevant
risks identified in the supplied contract.

RISK LEVEL:

The overall risk level must be exactly one of:

High
Medium
Low

IMPORTANT ACCURACY RULES:

- Base the analysis ONLY on the supplied contract.
- Do not invent clauses.
- Do not invent facts.
- Do not fabricate evidence.
- Do not paraphrase clause_text.
- Do not flag a clause merely because it contains a common legal keyword.
- Consider the surrounding context of the clause before assigning risk.
- A clause should be flagged because of its actual contractual meaning, not because
  of isolated words.
- Avoid unnecessary false positives.
- Prefer fewer well-supported findings over many weak findings.
- Every flagged clause must have a specific textual basis in the contract.

OUTPUT:

Return ONLY valid JSON matching the requested schema.

Do not include:
- Markdown
- Explanations outside JSON
- Comments
- Analysis
- Introductory text
"""


# ============================================================================
# GEMINI ANALYSIS
# ============================================================================

async def analyze_with_gemini(
    contract_text: str,
    filename: str,
    pages: List[ExtractedPage],
) -> ContractReport:

    # ------------------------------------------------------------------------
    # Check API key
    # ------------------------------------------------------------------------

    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        raise HTTPException(
            status_code=500,
            detail=(
                "GEMINI_API_KEY is missing. "
                "Add your Google AI Studio API key to the .env file."
            ),
        )

    try:

        # --------------------------------------------------------------------
        # Initialize Gemini client
        # --------------------------------------------------------------------

        client = genai.Client(
            api_key=api_key,
        )

        # --------------------------------------------------------------------
        # Build Gemini input
        #
        # IMPORTANT:
        # We no longer blindly truncate at 15,000 characters.
        #
        # Page-aware text is supplied so Gemini can understand the entire
        # available contract input within the model's context capacity.
        # --------------------------------------------------------------------

        analysis_text = contract_text

        user_prompt = (
            f"Filename: {filename}\n\n"
            f"Contract Text:\n{analysis_text}"
        )

        # --------------------------------------------------------------------
        # Structured output schema
        #
        # evidence_verified / match_confidence / matched_page are deliberately
        # NOT part of Gemini's schema.
        #
        # Vistara calculates those after Gemini responds.
        # --------------------------------------------------------------------

        response_schema = {
            "type": "OBJECT",
            "properties": {
                "filename": {
                    "type": "STRING",
                },
                "overall_score": {
                    "type": "INTEGER",
                },
                "risk_level": {
                    "type": "STRING",
                    "enum": [
                        "High",
                        "Medium",
                        "Low",
                    ],
                },
                "high_risk_count": {
                    "type": "INTEGER",
                },
                "medium_risk_count": {
                    "type": "INTEGER",
                },
                "low_risk_count": {
                    "type": "INTEGER",
                },
                "flagged_clauses": {
                    "type": "ARRAY",
                    "items": {
                        "type": "OBJECT",
                        "properties": {
                            "clause_text": {
                                "type": "STRING",
                            },
                            "severity": {
                                "type": "STRING",
                                "enum": [
                                    "High",
                                    "Medium",
                                    "Low",
                                ],
                            },
                            "category": {
                                "type": "STRING",
                            },
                            "plain_explanation": {
                                "type": "STRING",
                            },
                            "worst_case_scenario": {
                                "type": "STRING",
                            },
                        },
                        "required": [
                            "clause_text",
                            "severity",
                            "category",
                            "plain_explanation",
                            "worst_case_scenario",
                        ],
                    },
                },
            },
            "required": [
                "filename",
                "overall_score",
                "risk_level",
                "high_risk_count",
                "medium_risk_count",
                "low_risk_count",
                "flagged_clauses",
            ],
        }

        # --------------------------------------------------------------------
        # Gemini request
        # --------------------------------------------------------------------

        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                temperature=0.2,
                response_mime_type="application/json",
                response_schema=response_schema,
            ),
        )

        # --------------------------------------------------------------------
        # Get response text
        # --------------------------------------------------------------------

        if not response.text:
            raise HTTPException(
                status_code=500,
                detail="Gemini returned an empty response.",
            )

        # --------------------------------------------------------------------
        # Parse JSON
        # --------------------------------------------------------------------

        try:
            report_data = json.loads(
                response.text
            )

        except json.JSONDecodeError as e:
            print(
                "JSON Parsing Error:",
                e,
            )
            print(
                "Gemini response:",
                response.text,
            )

            raise HTTPException(
                status_code=500,
                detail="Gemini returned invalid JSON.",
            )

        # --------------------------------------------------------------------
        # Always trust actual uploaded filename
        # --------------------------------------------------------------------

        report_data["filename"] = filename

        # --------------------------------------------------------------------
        # Validate Gemini response using Pydantic
        # --------------------------------------------------------------------

        report = ContractReport(
            **report_data
        )

        # --------------------------------------------------------------------
        # IMPORTANT:
        #
        # Verify Gemini's evidence against the ACTUAL supplied document.
        #
        # This happens for:
        # - PDFs
        # - raw text
        # - other readable text files
        # --------------------------------------------------------------------

        verified_report = verify_report_evidence(
            report=report,
            pages=pages,
        )

        return verified_report

    # ------------------------------------------------------------------------
    # HTTP errors
    # ------------------------------------------------------------------------

    except HTTPException:
        raise

    # ------------------------------------------------------------------------
    # Gemini/API errors
    # ------------------------------------------------------------------------

    except Exception as e:

        error_text = str(e)

        print(
            "Gemini API Error:\n"
            f"{traceback.format_exc()}"
        )

        # --------------------------------------------------------------------
        # Quota / rate limit
        # --------------------------------------------------------------------

        if (
            "429" in error_text
            or "RESOURCE_EXHAUSTED" in error_text
            or "quota" in error_text.lower()
        ):
            raise HTTPException(
                status_code=429,
                detail=(
                    "Gemini API quota has been exceeded. "
                    "Please check your Google AI Studio project quota "
                    "or try again later."
                ),
            )

        # --------------------------------------------------------------------
        # Authentication
        # --------------------------------------------------------------------

        if (
            "401" in error_text
            or "UNAUTHENTICATED" in error_text
            or "authentication" in error_text.lower()
        ):
            raise HTTPException(
                status_code=401,
                detail=(
                    "Gemini API authentication failed. "
                    "Check that GEMINI_API_KEY in .env contains "
                    "a valid Google AI Studio API key."
                ),
            )

        # --------------------------------------------------------------------
        # General error
        # --------------------------------------------------------------------

        raise HTTPException(
            status_code=500,
            detail=(
                f"Gemini API analysis failed: "
                f"{error_text}"
            ),
        )


# ============================================================================
# ROOT ENDPOINT
# ============================================================================

@app.get("/")
async def root():
    return {
        "status": "ok",
        "message": (
            "Vistara Contract Analysis API "
            "(Gemini API Key Powered) is running"
        ),
    }


# ============================================================================
# ANALYZE ENDPOINT
# ============================================================================

@app.post(
    "/analyze",
    response_model=ContractReport,
)
async def analyze_contract(
    mock: bool = Query(False),
    file: Optional[UploadFile] = File(None),
    text: Optional[str] = Form(None),
):

    # ------------------------------------------------------------------------
    # Mock mode
    # ------------------------------------------------------------------------

    if mock:
        return MOCK_REPORT

    filename = "contract.txt"
    contract_text = ""
    extracted_pages: List[ExtractedPage] = []

    # ------------------------------------------------------------------------
    # FILE UPLOAD
    # ------------------------------------------------------------------------

    if file is not None:

        filename = file.filename or "upload.pdf"

        file_bytes = await file.read()

        if not file_bytes:
            raise HTTPException(
                status_code=422,
                detail="Uploaded file is empty.",
            )

        # --------------------------------------------------------------------
        # PDF
        # --------------------------------------------------------------------

        if filename.lower().endswith(".pdf"):

            try:

                extracted_pages = extract_pdf_pages(
                    file_bytes
                )

                contract_text = combine_pages(
                    extracted_pages
                )

            except Exception as e:

                print(
                    "PDF extraction error:"
                )
                print(
                    traceback.format_exc()
                )

                raise HTTPException(
                    status_code=422,
                    detail=(
                        f"Could not read PDF: {str(e)}"
                    ),
                )

        # --------------------------------------------------------------------
        # Other readable files
        # --------------------------------------------------------------------

        else:

            contract_text = file_bytes.decode(
                "utf-8",
                errors="replace",
            ).strip()

            extracted_pages = extract_text_input(
                contract_text
            )

    # ------------------------------------------------------------------------
    # RAW TEXT
    # ------------------------------------------------------------------------

    elif text:

        filename = "contract.txt"

        contract_text = text.strip()

        extracted_pages = extract_text_input(
            contract_text
        )

    # ------------------------------------------------------------------------
    # NOTHING SUPPLIED
    # ------------------------------------------------------------------------

    else:

        raise HTTPException(
            status_code=422,
            detail=(
                "Provide either a file upload "
                "or text in the request body."
            ),
        )

    # ------------------------------------------------------------------------
    # Validate extracted text
    # ------------------------------------------------------------------------

    if not contract_text.strip():

        raise HTTPException(
            status_code=422,
            detail=(
                "Could not extract any readable text "
                "from the provided input."
            ),
        )

    # ------------------------------------------------------------------------
    # DEBUG INFORMATION
    # ------------------------------------------------------------------------

    print(
        "========================================"
    )
    print(
        "VISTARA DOCUMENT EXTRACTION"
    )
    print(
        f"Filename: {filename}"
    )
    print(
        f"Pages/logical sections: "
        f"{len(extracted_pages)}"
    )
    print(
        f"Total characters: "
        f"{len(contract_text)}"
    )
    print(
        "========================================"
    )

    for page in extracted_pages:
        print(
            f"Page {page.page_number}: "
            f"{len(page.text)} characters"
        )

    # ------------------------------------------------------------------------
    # Gemini analysis
    # ------------------------------------------------------------------------

    return await analyze_with_gemini(
        contract_text=contract_text,
        filename=filename,
        pages=extracted_pages,
    )